export const DEFAULT_SESSION_TOKEN_FETCH_TIMEOUT_MS = 6_000;
export const DEFAULT_SESSION_TOKEN_FALLBACK_CACHE_TTL_MS = 30_000;
export const DEFAULT_SESSION_TOKEN_CACHE_TTL_MIN_MS = 5_000;
export const DEFAULT_SESSION_TOKEN_CACHE_TTL_MAX_MS = 300_000;
export const DEFAULT_SESSION_TOKEN_CACHE_TTL_FACTOR = 0.9;
export const DEFAULT_SESSION_USERINFO_CACHE_TTL_MS = 30_000;
